spring:
  profiles:
    active: dev  # ??????
  application:
    name: qqspeed-data-api

# MyBatis-Plus??
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  # ??????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # ??SQL??????
  global-config:
    db-config:
      id-type: auto  # ????
  mapper-locations: classpath:mapper/**/*.xml  # Mapper??????

# Knife4j????
knife4j:
  enable: true
  openapi:
    title: QQ???????API
    description: ??/??/??/???????
    version: 1.0.0
    contact:
      name: wangchao
      email: wangchao000413@qq.com
